## Nastavení proměnných
Zde nastav všechny proměnné:

In [11]:
# PODMÍNKA: povolit problem pri hledani cesty? 0 = nepovoleno
find_path_problem_podminka == 0

# PODMÍNKA: podíl ploch po rozdělení čtverce vodním tokem
nejlepsi_podil_ploch_max = 3 # 1/4 uzemi

# minimální počet průsečíků vodního toku a mřížky
pocet_pruseciku_min = 10

# PODMÍNKA: délka železnice
zeleznice_delka_min = 2000
zeleznice_delka_max = 15000

# PODMÍNKA: minimální délka rozvodncie III. řádu
rozvodniceIII_delka_min = 500 # v mapě linie 2 cm

# PODMÍNKA: výskyt vodní plochy, minimální délka
vodni_plohy_min = 62500 # 1cm2 v mapě
vodni_plohy_max = 500000 # 8cm2 v mapě = polovina malého čtverečku

# PODMÍNKA: maximalni povolena rozloha skal a povrchové těžby
relief_rozloha_max = 62500 # 1cm2 v mapě

# PODMÍNKA: výskyt zástavby
zastavba_rozloha_min = 62500 # 1cm2 v mapě

In [12]:
import pandas as pd
df = pd.read_csv(r"C:\fenclova\diplomka\analyza\git_diplomka\predvyber_vysledky\0_predvyber.csv", delimiter=";")
df.head()

,ID,find_path_problem,end_start_kombinace,nejlepsi_podil_ploch,pocet_pruseciku,zeleznice_delka,rozvodniceIII_delka,vodni_plohy_rozloha,relief_rozloha,zastavba_rozloha
0,1,0,20,643.16,3,7653.58,747.59,36261.96,5767.13,456577.71
1,2,0,12,1.57,19,10267.07,5409.23,138528.54,1145.86,129623.91
2,3,0,0,0.00,0,3685.11,4942.49,107350.63,2.00,259425.21
3,4,0,0,0.00,0,1395.98,7101.82,0.00,0.00,17419.58
4,5,24,63,21.61,9,3580.46,4451.48,64319.63,56606.64,374180.01

In [13]:
df.set_index('ID').head()

,find_path_problem,end_start_kombinace,nejlepsi_podil_ploch,pocet_pruseciku,zeleznice_delka,rozvodniceIII_delka,vodni_plohy_rozloha,relief_rozloha,zastavba_rozloha
ID,,,,,,,,,
1,0,20,643.16,3,7653.58,747.59,36261.96,5767.13,456577.71
2,0,12,1.57,19,10267.07,5409.23,138528.54,1145.86,129623.91
3,0,0,0.00,0,3685.11,4942.49,107350.63,2.00,259425.21
4,0,0,0.00,0,1395.98,7101.82,0.00,0.00,17419.58
5,24,63,21.61,9,3580.46,4451.48,64319.63,56606.64,374180.01

In [14]:
# kolik ctvercu ma find_path_problem?
find_path_problem_sum = df['find_path_problem'][df.find_path_problem > 0].shape[0]
find_path_problem_sum

182L

In [15]:
# kolik čtverců má podíl ploch v přípustném intervalu?
df[(df.nejlepsi_podil_ploch >=1) &
    (df.nejlepsi_podil_ploch <= 3)].shape

(304, 10)

In [16]:
# kolik čtverců má podíl ploch v intervalu? AND nebyl problem s vvýběrem?
df[(df.find_path_problem == 0) &
    (df.nejlepsi_podil_ploch >=1) &
    (df.nejlepsi_podil_ploch <= 3)].shape

(244, 10)

In [17]:
df[(df.find_path_problem == 0) &
    (df.nejlepsi_podil_ploch >=1) & (df.nejlepsi_podil_ploch <= 3) &
    (df.zeleznice_delka >=2000) & (df.zeleznice_delka <= 15000) &
   (df.rozvodniceIII_delka >= 2000) &
   (df.relief_rozloha <= 10000) &
   (df.vodni_plohy_rozloha > 0) &
   (df.zastavba_rozloha > 0)].describe()

,ID,find_path_problem,end_start_kombinace,nejlepsi_podil_ploch,pocet_pruseciku,zeleznice_delka,rozvodniceIII_delka,vodni_plohy_rozloha,relief_rozloha,zastavba_rozloha
count,78.000000,78.0,78.000000,78.000000,78.000000,78.000000,78.000000,7.800000e+01,78.000000,7.800000e+01
mean,401.628205,0.0,27.948718,1.758718,18.769231,6340.873718,4658.682179,3.376550e+05,1206.685256,1.569685e+06
std,216.892523,0.0,52.254844,0.594202,4.398710,3219.819144,2148.352745,5.516520e+05,2141.372173,1.266759e+06
min,2.000000,0.0,1.000000,1.010000,13.000000,2534.940000,2233.550000,7.270200e+02,0.000000,2.165666e+04
25%,240.250000,0.0,7.250000,1.280000,15.000000,4188.065000,2927.422500,6.037543e+04,0.000000,5.982537e+05
50%,408.500000,0.0,15.500000,1.660000,17.000000,5049.205000,4406.780000,1.550582e+05,0.000000,1.117872e+06
75%,558.750000,0.0,32.750000,2.070000,21.000000,7585.585000,5403.525000,3.656418e+05,1570.785000,2.374649e+06
max,792.000000,0.0,420.000000,2.990000,34.000000,14913.030000,11315.910000,3.280453e+06,7679.010000,5.154734e+06

In [18]:
df[(df.nejlepsi_podil_ploch >=1) & (df.nejlepsi_podil_ploch <= 3) &
    (df.zeleznice_delka >=2000) & (df.zeleznice_delka <= 15000) &
   (df.rozvodniceIII_delka >= 2000) &
   (df.relief_rozloha <= 10000) &
   (df.vodni_plohy_rozloha > 0) &
   (df.zastavba_rozloha > 0)].describe()

,ID,find_path_problem,end_start_kombinace,nejlepsi_podil_ploch,pocet_pruseciku,zeleznice_delka,rozvodniceIII_delka,vodni_plohy_rozloha,relief_rozloha,zastavba_rozloha
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,1.000000e+02,100.000000,1.000000e+02
mean,404.780000,3.730000,34.680000,1.741400,18.860000,6024.745200,4763.023900,3.891050e+05,1119.801900,1.517397e+06
std,217.694605,9.142922,51.269713,0.583487,4.369361,3022.699944,2330.701492,7.126637e+05,2071.087131,1.357950e+06
min,2.000000,0.000000,1.000000,1.000000,13.000000,2322.600000,2227.800000,4.942700e+02,0.000000,2.165666e+04
25%,232.500000,0.000000,8.000000,1.245000,15.750000,4173.227500,2876.187500,5.813830e+04,0.000000,5.683613e+05
50%,425.000000,0.000000,20.000000,1.650000,18.000000,4973.055000,4406.780000,1.434340e+05,0.000000,1.059177e+06
75%,557.250000,0.000000,40.000000,2.050000,21.000000,6909.802500,5427.575000,3.759443e+05,1542.682500,2.063435e+06
max,813.000000,60.000000,420.000000,2.990000,34.000000,14913.030000,11315.910000,4.581831e+06,7679.010000,7.521177e+06

In [19]:
df[(df.pocet_pruseciku >= 13) &
    (df.zeleznice_delka >=2000) & 
   (df.zeleznice_delka <= 15000) &
   (df.rozvodniceIII_delka >= 2000) &
   (df.relief_rozloha <= 10000) &
   (df.vodni_plohy_rozloha > 0) &
   (df.zastavba_rozloha > 0)].describe()
# když beru podíl plochy do 3, je min pocet průsečíků = 13
# když nastavím místo plochy počet průsečíků, získám o 69 více čtverců

,ID,find_path_problem,end_start_kombinace,nejlepsi_podil_ploch,pocet_pruseciku,zeleznice_delka,rozvodniceIII_delka,vodni_plohy_rozloha,relief_rozloha,zastavba_rozloha
count,147.000000,147.000000,147.000000,147.000000,147.00000,147.000000,147.000000,1.470000e+02,147.000000,1.470000e+02
mean,418.122449,3.551020,34.061224,2.750272,17.77551,5573.791769,4772.758435,3.289581e+05,1057.237483,1.354710e+06
std,228.263933,8.285309,45.313554,1.774825,4.37583,2925.075591,2107.346872,6.238816e+05,2036.616597,1.212154e+06
min,2.000000,0.000000,1.000000,1.000000,13.00000,2035.440000,2015.700000,4.942700e+02,0.000000,2.165666e+04
25%,211.500000,0.000000,10.000000,1.395000,14.00000,3959.870000,3073.950000,5.849138e+04,0.000000,5.426958e+05
50%,429.000000,0.000000,21.000000,2.040000,16.00000,4689.410000,4609.230000,1.224426e+05,0.000000,9.490175e+05
75%,590.000000,0.000000,40.000000,3.510000,20.00000,6340.485000,5481.065000,3.271830e+05,1533.255000,1.703436e+06
max,866.000000,60.000000,420.000000,9.060000,34.00000,14913.030000,11315.910000,4.581831e+06,9540.410000,7.521177e+06

In [20]:
df[(df.pocet_pruseciku >= 10) &
    (df.nejlepsi_podil_ploch >=1) & (df.nejlepsi_podil_ploch <= 5) & # chci dělit plochu řekou
    (df.zeleznice_delka >=500) & # 2 cm v mapě
   #(df.zeleznice_delka <= 15000) & # maximum délky železnice
   (df.rozvodniceIII_delka >= 500) & # 2 cm v mapě
   (df.relief_rozloha <= 5) & # omezit skály a těžbu (nejsou tam vrstevnice)
   (df.vodni_plohy_rozloha > 500) & # chci vodní plochu
   (df.zastavba_rozloha > 500) # chci zástavbu
  ].describe()

,ID,find_path_problem,end_start_kombinace,nejlepsi_podil_ploch,pocet_pruseciku,zeleznice_delka,rozvodniceIII_delka,vodni_plohy_rozloha,relief_rozloha,zastavba_rozloha
count,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,1.360000e+02,136.000000,1.360000e+02
mean,397.676471,3.367647,31.110294,2.169485,18.080882,6014.331250,4263.248529,2.906645e+05,0.176471,1.493624e+06
std,216.863940,7.267185,32.478066,1.036798,4.891497,5512.202048,2639.536578,5.269233e+05,0.778244,1.521940e+06
min,14.000000,0.000000,1.000000,1.000000,10.000000,591.510000,512.760000,7.270200e+02,0.000000,4.271896e+04
25%,197.000000,0.000000,9.000000,1.317500,14.750000,3005.880000,2427.835000,5.617498e+04,0.000000,5.720533e+05
50%,427.500000,0.000000,20.500000,1.850000,17.000000,4455.505000,3927.300000,1.236789e+05,0.000000,1.011561e+06
75%,559.750000,0.000000,42.000000,2.760000,20.000000,6705.760000,5352.882500,3.271538e+05,0.000000,1.617262e+06
max,802.000000,38.000000,162.000000,4.830000,37.000000,34258.260000,16793.610000,4.581831e+06,5.000000,7.961439e+06